### ISSUE TITLE
Parenthesis handling

### ISSUE THREAD

**Issue by Proffitt** [bmos/FG-PFRPG-Upgrade-NPC-Actions#14]
I submitted a PR for your review. It changes the parenthesis so that it can handle multiple in a name because that's what I'm getting in the Reign of Winter AP. i.e. "(1/day) slow (DC 17)".

**Comment by bmos** [comment]
Thanks, i haven't seen a good "cheat sheet" for -, +, and so forth so I've struggled with this issue.
